[theme]
primaryColor = "#4A90E2"        # soft blue
backgroundColor = "#FFFFFF"     # white
secondaryBackgroundColor = "#F5F8FA"  # light grey-blue
textColor = "#0A1F44"           # dark navy
font = "sans serif"